services:
  postgres:
    image: postgres:16-alpine
    container_name: debezium-poc-postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: debezium-poc-mssql
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     MSSQL_SA_PASSWORD: "yourStrong(!)Password"
  #     MSSQL_PID: Developer
  #   ports:
  #     - 1433:1433
  #   volumes:
  #     - mssql_data:/var/opt/mssql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.10
    container_name: debezium-poc-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.10
    container_name: debezium-poc-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 29092:29092
      - 9092:9092
    depends_on:
      - zookeeper

  connect:
    image: quay.io/debezium/connect:3.1
    container_name: debezium-poc-connect
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      # KEY_CONVERTER_SCHEMAS_ENABLE: false
      # VALUE_CONVERTER_SCHEMAS_ENABLE: false
      # KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      # VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      # CONNECT_REST_ADVERTISED_HOST_NAME: connect
      # CONNECT_PLUGIN_PATH: /kafka/connect,/debezium
    depends_on:
      - postgres
      - kafka

volumes:
  postgres_data:
  # mssql_data:
